// BREAKPOINT
export const BREAKPOINT_SM = 'sm'
export const BREAKPOINT_MD = 'md'
export const BREAKPOINT_LG = 'lg'
export const BREAKPOINT_XL = 'xl'
export const BREAKPOINTS = [
    BREAKPOINT_SM,
    BREAKPOINT_MD,
    BREAKPOINT_LG,
    BREAKPOINT_XL,
] as const

export const TW_BREAKPOINT_NO_PREFIX = ``
export const TW_BREAKPOINT_SM_PREFIX = `${BREAKPOINT_SM}:`
export const TW_BREAKPOINT_MD_PREFIX = `${BREAKPOINT_MD}:`
export const TW_BREAKPOINT_LG_PREFIX = `${BREAKPOINT_LG}:`
export const TW_BREAKPOINT_XL_PREFIX = `${BREAKPOINT_XL}:`
export const TW_BREAKPOINTS = [
    TW_BREAKPOINT_NO_PREFIX,
    TW_BREAKPOINT_SM_PREFIX,
    TW_BREAKPOINT_MD_PREFIX,
    TW_BREAKPOINT_LG_PREFIX,
    TW_BREAKPOINT_XL_PREFIX,
] as const

// STYLE
export const STYLE_COLOR = 'color'
export const STYLE_TEXT_ALIGN = 'text-align'
export const STYLE_FONT_FAMILY = 'font-family'
export const STYLE_FONT_SIZE = 'font-size'
export const STYLE_FONT_WEIGHT = 'font-weight'
export const STYLE_FONT_STYLE = 'font-style'
export const STYLE_WIDTH = 'width'
export const STYLE_HEIGHT = 'height'

// BACKGROUND
export const STYLING_BACKGROUND_SUFFIX = '-background'
export const STYLING_BACKGROUND_SM = `--${BREAKPOINT_SM}${STYLING_BACKGROUND_SUFFIX}`
export const STYLING_BACKGROUND_MD = `--${BREAKPOINT_MD}${STYLING_BACKGROUND_SUFFIX}`
export const STYLING_BACKGROUND_LG = `--${BREAKPOINT_LG}${STYLING_BACKGROUND_SUFFIX}`
export const STYLING_BACKGROUND_XL = `--${BREAKPOINT_XL}${STYLING_BACKGROUND_SUFFIX}`
export const STYLING_BACKGROUNDS = [
    STYLING_BACKGROUND_SM,
    STYLING_BACKGROUND_MD,
    STYLING_BACKGROUND_LG,
    STYLING_BACKGROUND_XL,
] as const

// POS X
export const STYLING_POS_X_SUFFIX = '-pos-x'
export const STYLING_POS_X_SM = `--${BREAKPOINT_SM}${STYLING_POS_X_SUFFIX}`
export const STYLING_POS_X_MD = `--${BREAKPOINT_MD}${STYLING_POS_X_SUFFIX}`
export const STYLING_POS_X_LG = `--${BREAKPOINT_LG}${STYLING_POS_X_SUFFIX}`
export const STYLING_POS_X_XL = `--${BREAKPOINT_XL}${STYLING_POS_X_SUFFIX}`
export const STYLING_POS_XS = [
    STYLING_POS_X_SM,
    STYLING_POS_X_MD,
    STYLING_POS_X_LG,
    STYLING_POS_X_XL,
] as const

// POS Y
export const STYLING_POS_Y_SUFFIX = '-pos-y'
export const STYLING_POS_Y_SM = `--${BREAKPOINT_SM}${STYLING_POS_Y_SUFFIX}`
export const STYLING_POS_Y_MD = `--${BREAKPOINT_MD}${STYLING_POS_Y_SUFFIX}`
export const STYLING_POS_Y_LG = `--${BREAKPOINT_LG}${STYLING_POS_Y_SUFFIX}`
export const STYLING_POS_Y_XL = `--${BREAKPOINT_XL}${STYLING_POS_Y_SUFFIX}`
export const STYLING_POS_YS = [
    STYLING_POS_Y_SM,
    STYLING_POS_Y_MD,
    STYLING_POS_Y_LG,
    STYLING_POS_Y_XL,
] as const

// COLOR
export const STYLING_COLOR_SUFFIX = `-${STYLE_COLOR}`
export const STYLING_COLOR_SM = `--${BREAKPOINT_SM}${STYLING_COLOR_SUFFIX}`
export const STYLING_COLOR_MD = `--${BREAKPOINT_MD}${STYLING_COLOR_SUFFIX}`
export const STYLING_COLOR_LG = `--${BREAKPOINT_LG}${STYLING_COLOR_SUFFIX}`
export const STYLING_COLOR_XL = `--${BREAKPOINT_XL}${STYLING_COLOR_SUFFIX}`
export const STYLING_COLORS = [
    STYLING_COLOR_SM,
    STYLING_COLOR_MD,
    STYLING_COLOR_LG,
    STYLING_COLOR_XL,
] as const

// TEXT_ALIGN
export const STYLING_TEXT_ALIGN_SUFFIX = `-${STYLE_TEXT_ALIGN}`
export const STYLING_TEXT_ALIGN_SM = `--${BREAKPOINT_SM}${STYLING_TEXT_ALIGN_SUFFIX}`
export const STYLING_TEXT_ALIGN_MD = `--${BREAKPOINT_MD}${STYLING_TEXT_ALIGN_SUFFIX}`
export const STYLING_TEXT_ALIGN_LG = `--${BREAKPOINT_LG}${STYLING_TEXT_ALIGN_SUFFIX}`
export const STYLING_TEXT_ALIGN_XL = `--${BREAKPOINT_XL}${STYLING_TEXT_ALIGN_SUFFIX}`
export const STYLING_TEXT_ALIGNSS = [
    STYLING_TEXT_ALIGN_SM,
    STYLING_TEXT_ALIGN_MD,
    STYLING_TEXT_ALIGN_LG,
    STYLING_TEXT_ALIGN_XL,
] as const

// FONT FAMILY
// export const STYLING_FONT_FAMILY_SUFFIX = `-${STYLE_FONT_FAMILY}`
// export const STYLING_FONT_FAMILY_SM = `--${BREAKPOINT_SM}${STYLING_FONT_FAMILY_SUFFIX}`
// export const STYLING_FONT_FAMILY_MD = `--${BREAKPOINT_MD}${STYLING_FONT_FAMILY_SUFFIX}`
// export const STYLING_FONT_FAMILY_LG = `--${BREAKPOINT_LG}${STYLING_FONT_FAMILY_SUFFIX}`
// export const STYLING_FONT_FAMILY_XL = `--${BREAKPOINT_XL}${STYLING_FONT_FAMILY_SUFFIX}`
// export const STYLING_FONT_FAMILIES = [
//     STYLING_FONT_FAMILY_SM,
//     STYLING_FONT_FAMILY_MD,
//     STYLING_FONT_FAMILY_LG,
//     STYLING_FONT_FAMILY_XL,
// ] as const

// FONT SIZE
export const STYLING_FONT_SIZE_SUFFIX = `-${STYLE_FONT_SIZE}`
export const STYLING_FONT_SIZE_SM = `--${BREAKPOINT_SM}${STYLING_FONT_SIZE_SUFFIX}`
export const STYLING_FONT_SIZE_MD = `--${BREAKPOINT_MD}${STYLING_FONT_SIZE_SUFFIX}`
export const STYLING_FONT_SIZE_LG = `--${BREAKPOINT_LG}${STYLING_FONT_SIZE_SUFFIX}`
export const STYLING_FONT_SIZE_XL = `--${BREAKPOINT_XL}${STYLING_FONT_SIZE_SUFFIX}`
export const STYLING_FONT_SIZES = [
    STYLING_FONT_SIZE_SM,
    STYLING_FONT_SIZE_MD,
    STYLING_FONT_SIZE_LG,
    STYLING_FONT_SIZE_XL,
] as const

// FONT WEIGHT
export const STYLING_FONT_WEIGHT_SUFFIX = `-${STYLE_FONT_WEIGHT}`
export const STYLING_FONT_WEIGHT_SM = `--${BREAKPOINT_SM}${STYLING_FONT_WEIGHT_SUFFIX}`
export const STYLING_FONT_WEIGHT_MD = `--${BREAKPOINT_MD}${STYLING_FONT_WEIGHT_SUFFIX}`
export const STYLING_FONT_WEIGHT_LG = `--${BREAKPOINT_LG}${STYLING_FONT_WEIGHT_SUFFIX}`
export const STYLING_FONT_WEIGHT_XL = `--${BREAKPOINT_XL}${STYLING_FONT_WEIGHT_SUFFIX}`
export const STYLING_FONT_WEIGHTS = [
    STYLING_FONT_WEIGHT_SM,
    STYLING_FONT_WEIGHT_MD,
    STYLING_FONT_WEIGHT_LG,
    STYLING_FONT_WEIGHT_XL,
] as const

// FONT STYLE
export const STYLING_FONT_STYLE_SUFFIX = `-${STYLE_FONT_STYLE}`
export const STYLING_FONT_STYLE_SM = `--${BREAKPOINT_SM}${STYLING_FONT_STYLE_SUFFIX}`
export const STYLING_FONT_STYLE_MD = `--${BREAKPOINT_MD}${STYLING_FONT_STYLE_SUFFIX}`
export const STYLING_FONT_STYLE_LG = `--${BREAKPOINT_LG}${STYLING_FONT_STYLE_SUFFIX}`
export const STYLING_FONT_STYLE_XL = `--${BREAKPOINT_XL}${STYLING_FONT_STYLE_SUFFIX}`
export const STYLING_FONT_STYLES = [
    STYLING_FONT_STYLE_SM,
    STYLING_FONT_STYLE_MD,
    STYLING_FONT_STYLE_LG,
    STYLING_FONT_STYLE_XL,
] as const

// WIDTH
export const STYLING_WIDTH_SUFFIX = `-${STYLE_WIDTH}`
export const STYLING_WIDTH_SM = `--${BREAKPOINT_SM}${STYLING_WIDTH_SUFFIX}`
export const STYLING_WIDTH_MD = `--${BREAKPOINT_MD}${STYLING_WIDTH_SUFFIX}`
export const STYLING_WIDTH_LG = `--${BREAKPOINT_LG}${STYLING_WIDTH_SUFFIX}`
export const STYLING_WIDTH_XL = `--${BREAKPOINT_XL}${STYLING_WIDTH_SUFFIX}`
export const STYLING_WIDTHS = [
    STYLING_WIDTH_SM,
    STYLING_WIDTH_MD,
    STYLING_WIDTH_LG,
    STYLING_WIDTH_XL,
] as const

// HEIGHT
export const STYLING_HEIGHT_SUFFIX = `-${STYLE_HEIGHT}`
export const STYLING_HEIGHT_SM = `--${BREAKPOINT_SM}${STYLING_HEIGHT_SUFFIX}`
export const STYLING_HEIGHT_MD = `--${BREAKPOINT_MD}${STYLING_HEIGHT_SUFFIX}`
export const STYLING_HEIGHT_LG = `--${BREAKPOINT_LG}${STYLING_HEIGHT_SUFFIX}`
export const STYLING_HEIGHT_XL = `--${BREAKPOINT_XL}${STYLING_HEIGHT_SUFFIX}`
export const STYLING_HEIGHTS = [
    STYLING_HEIGHT_SM,
    STYLING_HEIGHT_MD,
    STYLING_HEIGHT_LG,
    STYLING_HEIGHT_XL,
] as const

export const STYLING_SUFFIXES = [
    STYLING_BACKGROUND_SUFFIX,
    STYLING_POS_X_SUFFIX,
    STYLING_POS_Y_SUFFIX,
    STYLING_COLOR_SUFFIX,
    STYLING_TEXT_ALIGN_SUFFIX,
    // STYLING_FONT_FAMILY_SUFFIX,
    STYLING_FONT_SIZE_SUFFIX,
    STYLING_FONT_WEIGHT_SUFFIX,
    STYLING_FONT_STYLE_SUFFIX,
    STYLING_WIDTH_SUFFIX,
    STYLING_HEIGHT_SUFFIX,
] as const
